societies/urls.py
# -*- coding: utf-8 -*-
"""
societies.urls
~~~~~~~~~~~~~~

:copyright: (c) 2014 Christopher Davis <http://christopherdavis.me>
:license: http://opensource.org/licenses/bsd-3-clause
"""

from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^country/(?P<country>[a-z]{2})$', views.country, name='country'),
    url(r'^issue/(?P<socid>\d+)$', views.issue, name='issue'),
    url(r'^go/(?P<socid>\d+)$', views.single, name='single'),
)

website/urls.py
# -*- coding: utf-8 -*-
"""
GuitarSocieties.org
~~~~~~~~~~~~~~~~~~~

:copyright: (c) 2014 Christopher Davis <http://christopherdavis.me>
:license: http://opensource.org/licenses/bsd-3-clause
"""

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

admin.site.site_header = _('Guitar Societies')
admin.site.site_title = _('Guitar Societies')
admin.site.index_title = _('Guitar Society Admin')

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('societies.urls', namespace='societies')),
)

societies/models.py
# -*- coding: utf-8 -*-
"""
societies.models
~~~~~~~~~~~~~~~~

:copyright: (c) 2014 Christopher Davis <http://christopherdavis.me>
:license: http://opensource.org/licenses/bsd-3-clause
"""

from django.db import models
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _


class GuitarSociety(models.Model):
    """
    Represents a single guitar society.

    .. versionadded:: 0.1
    """

    class Meta:
        verbose_name_plural = _('Guitar Societies')

    #: the name of the society
    #: ..versionadded:: 0.1
    name = models.CharField(max_length=1024)

    #: the society's url
    #: ..versionadded:: 0.1
    link = models.URLField(max_length=255)

    #: The country in which the society resides
    #: .. versionadded:: 0.1
    country = CountryField()

    #: A free form "city" or "region" field used to display where
    #: exactly the society is within a country
    #: .. versionadded:: 0.1
    region = models.CharField(max_length=512, null=True, default=None, blank=True)

    #: When the guitar society was first added.
    #: .. versionadded:: 0.1
    created = models.DateTimeField(auto_now_add=True)

    #: Whether or not the guitar society is active (can be displayed on the frontend).
    #: .. versionadded:: 0.1
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<GuitarSociety("{}")>'.format(self.name)


class Issue(models.Model):
    """
    Represents a "issue" with a guitar society -- reporting a problem, etc.

    .. versionadded:: 0.1
    """

    class Meta:
        ordering = ['-created']

    BROKEN_LINK = 'link'
    INCORRECT_NAME = 'name'
    INCORRECT_REGION = 'region'
    CUSTOM_ISSUE = 'custom'
    TYPE_CHOICES = (
        (BROKEN_LINK, _('Broken Link')),
        (INCORRECT_NAME, _('Incorrect Name')),
        (INCORRECT_REGION, _('Incorrect Region')),
        (CUSTOM_ISSUE, _('Custom (Please Explain)')),
    )

    #: the society to which the issue belongs
    #: .. versionadded:: 0.1
    society = models.ForeignKey(GuitarSociety, on_delete=models.CASCADE)

    #: What kind of issue we're ding with
    #: .. versionadded:: 0.1
    issue_type = models.CharField(max_length=12, choices=TYPE_CHOICES, default=BROKEN_LINK)

    #: A longer description of the issue, maybe be blank
    #: .. versionadded:: 0.1
    description = models.TextField(null=True, blank=True, default=None)

    #: When the issue was created
    #: .. versionadded:: 01
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.issue_type, self.society)

    def __repr__(self):
        return '<Issue("{}", {})>'.format(self.issue_type, repr(self.society))

societies/forms.py
# -*- coding: utf-8 -*-
"""
societies.forms
~~~~~~~~~~~~~~~

:copyright: (c) 2014 Christopher Davis <http://christopherdavis.me>
:license: http://opensource.org/licenses/bsd-3-clause
"""

from django import forms
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _
from .models import Issue


class SubmitIssueForm(forms.ModelForm):
    """
    Frontend form for reporting an issue with a guitar society.

    .. versionadded:: 0.1
    """

    class Meta:
        model = Issue
        fields = ('issue_type', 'description',)

    def clean(self):
        cleaned = super().clean()
        typ = cleaned.get('issue_type')
        desc = cleaned.get('description')
        if Issue.CUSTOM_ISSUE == typ and not desc:
            self.add_error('description', _('Please describe the issue.'))

    def clean_description(self):
        description = self.cleaned_data.get('description')
        return strip_tags(description) if description else None

societies/views.py
# -*- coding: utf-8 -*-
"""
societies.views
~~~~~~~~~~~~~~~

:copyright: (c) 2014 Christopher Davis <http://christopherdavis.me>
:license: http://opensource.org/licenses/bsd-3-clause
"""

from collections import OrderedDict
import urllib.parse as urlparse
from django.contrib import messages
from django.shortcuts import get_object_or_404, get_list_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _
from django_countries import countries
from .forms import SubmitIssueForm
from .models import GuitarSociety, Issue


def _get_all_societies():
    all_societies = GuitarSociety.objects.filter(active=True).order_by('country', 'region')
    societies = OrderedDict()
    for soc in all_societies:
        societies.setdefault(soc.country, list()).append(soc)
    return societies


def _get_society(socid):
    return get_object_or_404(GuitarSociety, pk=socid, active=True)


def index(request):
    """
    Show every guitar society in our database.

    .. versionadded:: 0.1

    :param request: the django request object
    """
    societies = _get_all_societies()

    return render(request, 'societies/index.html', {
        'all_societies': societies,
    })


def country(request, country):
    societies = get_list_or_404(GuitarSociety.objects.filter(active=True), country=country.upper())
    country = societies[0].country

    return render(request, 'societies/country.html', {
        'societies': societies,
        'all_societies': _get_all_societies(),
        'country': country
    })


def issue(request, socid):
    society = _get_society(socid)
    issue = Issue(society=society)
    if 'POST' == request.method:
        form = SubmitIssueForm(request.POST, instance=issue)
        if form.is_valid():
            issue.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                _('Issue reported! Thank you.'),
                extra_tags='success',
            )
            return redirect('societies:index')
    else:
        form = SubmitIssueForm(instance=issue)

    return render(request, 'societies/issue.html', {
        'society': society,
        'form': form,
        'all_societies': _get_all_societies(),
    })


def single(request, socid):
    society = _get_society(socid)
    scheme, netloc, path, query, frag = urlparse.urlsplit(society.link)
    query = urlparse.parse_qs(query, keep_blank_values=True)
    query.update({
        'utm_source': 'guitarsocieties.org',
        'utm_medium': 'website',
        'utm_campaign': 'guitarsocieties',
    })
    return redirect(urlparse.urlunsplit((
        scheme,
        netloc,
        path,
        urlparse.urlencode(query, doseq=True),
        frag,
    )))

societies/templates/societies/base.html
{% extends 'layout.html' %}

{% load i18n %}

{% block main_navigation %}
<div class="small-12 columns">
    <nav class="top-bar" data-topbar role="navigation">

        <section class="top-bar-section">
            <ul>
                <li><a href="{% url 'societies:index' %}">Home</a></li>
                <li class="has-dropdown">
                    <a href="#">{% trans "Countries" %}</a>
                    <ul class="dropdown">
                        {% for country in all_societies %}
                        <li>
                            <a href="{% url 'societies:country' country.code|lower %}">{{ country.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </section>

    </nav>
</div>
{% endblock %}

{% block body %}
<div class="small-12 columns">
    {% block messages %}
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div data-alert class="alert-box {{ message.tags }}">
                {{ message }}
                <a href="#" class="close">&times;</a>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endblock %}

    {% block society_body %}{% endblock %}
</div>
{% endblock %}

societies/templates/societies/country.html
{% extends 'societies/base.html' %}

{% load i18n %}

{% block headtitle %}{{ country.name }} {% trans "Classical Guitar Societies" %}{% endblock %}

{% block page_subtitle %}<h4>{{ country.name }}</h4>{% endblock %}

{% block headmeta %}
<meta name="description" content="{% trans "Visit ClassicalGuitar.org to find a classical guitar society in" %} {{ country.name }}." />
<meta property="og:title" content="{{ country.name }} {% trans "Classical Guitar Societies." %}" />
<meta property="og:description" content="{% trans "Visit ClassicalGuitar.org to find a classical guitar society in" %} {{ country.name}}." />
{% endblock %}

{% block society_body %}
    <ul class="no-bullet society-list">
    {% for society in societies %}
        <li>
            <a href="{% url 'societies:single' society.id %}">{{ society.name }}</a>
            {% if society.region %}&mdash; <em>{{ society.region }}</em>{% endif %}
            <a class="report" href="{% url 'societies:issue' society.id %}"><small>Issues?</small></a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

societies/templates/societies/index.html
{% extends 'societies/base.html' %}

{% load i18n %}

{% block headtitle %}{% trans "Find a Classical Guitar Society" %}{% endblock %}

{% block headmeta %}
<meta name="description" content="{% trans "Visit GuitarSocieties.org to find a classical guitar society near you." %}" />
<meta property="og:title" content="{% trans "List of Classical Guitar Societies" %}" />
<meta property="og:description" content="{% trans "Visit GuitarSocieties.org to find a classical guitar society near you." %}" />
{% endblock %}

{% block society_body %}
    <dl class="society-list">
    {% for country, societies in all_societies.items %}
        <dt><a href="{% url 'societies:country' country.code|lower %}">{{ country.name }}</a></dt>
        {% for society in societies %}
            <dd>
                <a href="{% url 'societies:single' society.id %}">{{ society.name }}</a>
                {% if society.region %}&mdash; <em>{{ society.region }}</em>{% endif %}
                <a class="report" href="{% url 'societies:issue' society.id %}"><small>Issues?</small></a>
            </dd>
        {% endfor %}
    {% endfor %}
    </ul>
{% endblock %}

societies/templates/societies/issue.html
{% extends 'societies/base.html' %}

{% load i18n %}

{% block headtitle %}{% trans "Report an Issue with" %} {{ society.name }}{% endblock %}

{% block headmeta %}
<meta name="robots" content="noindex,follow" />
{% endblock %}

{% block society_body %}
<h3>{% trans "Report an Issue" %} <small>{{ society.name }}</small></h3>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="button primary small">{% trans "Submit Issue" %}</button>
</form>

{% endblock %}

website/templates/layout.html
{% load staticfiles i18n %}
<!DOCTYPE html{%block doctype %}{% endblock %}>
<html dir="ltr" lang="en-us" prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block headtitle %}{% endblock %} :: GuitarSocieties.org</title>
    <meta property="og:type" content="{% block headogtype %}website{% endblock %}" />
    <meta property="og:sitename" content="GuitarSocieties.org" />
    {% block headmeta %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    {% block stylesheets %}{% endblock %}

    <script src="{% static 'vendor/modernizr/modernizr.js' %}"></script>
    <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/fastclick/lib/fastclick.js' %}"></script>
    <script src="{% static 'vendor/foundation/js/foundation.min.js' %}"></script>
    <script>
        $(document).ready(function () { $(document).foundation(); });
    </script>
    {% block scripts %}{% endblock %}
</head>
<body class="{% block bodyclass %}{% endblock %}>">
    {% block main_header %}
    <header id="header">
        <div class="row title-row">
            <div class="small-12 columns">
                <h1 class="branding">{% block page_title %}{% trans "Classical Guitar Societies" %}{% endblock %}</h1>
                {% block page_subtitle %}{% endblock %}
            </div>
        </div>
        <div class="row">
            {% block main_navigation %}{% endblock %}
        </div>
    </header>
    {% endblock %}

    <div id="main">
        <div class="row">
            {% block body %}{% endblock %}
        </div>
    </div>

    {% block main_footer %}
    <footer id="footer" class="row">
        <div class="small-12 columns">
            <p>
                <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
                    <img alt="{% trans 'Creative Commons License' %}" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
                </a>
            </p>
            <p>
                {% trans "Website by" %}
                <a href="http://christopherdavis.me" rel="external">Christopher Davis</a>.
            </p>
        </div>
    </footer>
    {% endblock %}

    {% block footer_scripts %}{% endblock %}
</body>
</html>